[package]
name = "pasta_curves"
description = "Implementation of the Pallas and Vesta (Pasta) curve cycle"
version = "0.1.0"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Ying Tong Lai <yingtong@electriccoin.co>",
    "Daira Hopwood <daira@electriccoin.co>",
    "Jack Grigg <jack@electriccoin.co>",
]
edition = "2018"
license-file = "LICENSE-BOSL"
repository = "https://github.com/zcash/pasta_curves"
documentation = "https://docs.rs/pasta_curves"
readme = "README.md"
exclude = ["Contributor_Agreement"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[dev-dependencies]
criterion = "0.3"
rand_xorshift = "0.3"

[[bench]]
name = "hashtocurve"
harness = false
required-features = ["alloc"]

[[bench]]
name = "fp"
harness = false

[[bench]]
name = "fq"
harness = false

[dependencies]
subtle = "2.3"
ff = "0.10"
group = "0.10"
rand = "0.8"
blake2b_simd = "0.5"
static_assertions = "1.1.0"

# alloc dependencies
lazy_static = { version = "1.4.0", optional = true }

[features]
default = ["bits", "std"]
alloc = ["lazy_static"]
bits = ["ff/bits"]
std = ["alloc"]
